---
- hosts: backend
  become: yes
  gather_facts: no
  tasks:
    - name: disable SELinux
      command: setenforce 0
    - name: install apache
      ansible.builtin.yum:
        update_cache: yes
        name:
          - unzip
          - httpd
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
          - yum-utils
          - php-mysql
    - name: start apache
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes
    - ansible.builtin.command: yum-config-manager --enable remi-php74
    - name: install php
      ansible.builtin.yum:
        name:
          - php
          - php-cli
    - name: download wordpress
      ansible.builtin.get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip
    - name: unzip
      ansible.builtin.unarchive:
        src: /tmp/wordpress.zip
        dest: /var/www/html
        owner: apache
        group: apache
        remote_src: yes
    - name: wp-config.php
      ansible.builtin.template:
        src: wp-config-sample.php.j2
        dest: /var/www/html/wordpress/wp-config.php
    - name: restart apache
      ansible.builtin.systemd:
        name: httpd
        state: restarted
    - name: wait
      ansible.builtin.wait_for:
        port: '{{load_balancer_port}}'
        state: started
        delay: 0
        timeout: 3
      ignore_errors: yes
