---
- hosts: nginx
- hosts: db
  become: true
  gather_facts: no
  tasks:
    - ansible.builtin.yum:
        name: 
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          - https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    - name: install postgresql
      ansible.builtin.yum:
        name: postgresql15-server
    - ansible.builtin.file:
        path: /var/lib/pgsql/15/data/
        state: absent
    - name: initdb
      command: /usr/pgsql-15/bin/postgresql-15-setup initdb
    - name: start postgresql
      ansible.builtin.systemd:
        name: postgresql-15
        state: started
        enabled: yes
