---
- hosts: nginx
  become: true
  gather_facts: no
  tasks:
    - name: install keepalived
      ansible.builtin.yum:
        update_cache: yes
        name:
          - keepalived
    - name: sysctl
      ansible.posix.sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: '1'
        state: present
    - ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_instance VI_1 {
            state {{ keepalived_state }}
            interface eth0
            virtual_router_id 51
            priority 100
            virtual_ipaddress {
              10.0.26.80
            }
          }
    - ansible.builtin.systemd:
        name: keepalived
        state: started
        enabled: yes
