---
- name: Prepare server
  become: true
  hosts: server
  tasks:
    - name: Install targetcli
      ansible.builtin.yum:
        state: latest
        pkg:
          - targetcli
    - name: Create file
      community.general.filesize:
        path: /var/run/disk
        size: 1G
    - name: Map disk
      command: targetcli /backstores/fileio create disk01 /var/run/disk
      ignore_errors: true
    - name: Create target
      command: targetcli /iscsi create iqn.2018-09.ru.otus:storage.target00
      ignore_errors: true
    - name: Create LUN
      command: targetcli /iscsi/iqn.2018-09.ru.otus:storage.target00/tpg1/luns create /backstores/fileio/disk01
      ignore_errors: true
- name: Prepare clients
  become: true
  hosts: clients
  tasks:
    - name: Install pacemaker
      ansible.builtin.yum:
        name:
          - pacemaker
          - pcs
          - fence-agents-all
          - iscsi-initiator-utils
          - lvm2-cluster
          - gfs2-utils
    - name: Start pacemaker
      ansible.builtin.systemd:
        name: pcsd
        state: started
        enabled: true
    - name: Set hacluster password
      ansible.builtin.user:
        name: hacluster
        password: $6$mysecretsalt$2PO0ANor95BEjI5Df1m7NeKkzF1s5xkb7wvuJKdQc59S1fY0JQcHadoT0wRjIhCDVcOTzkR8DDkmxn1rurx5w1
    - name: Auth to pcs
      command: pcs cluster auth {{ clients }} -u hacluster -p hacluster_pwd
    - name: Setup pcs
      command: pcs cluster setup --name otuscluster {{ clients }}
      ignore_errors: true
    - name: Enable pcs
      command: pcs cluster enable --all
    - name: Start pcs
      command: pcs cluster start --all

    - name: Discover target
      command: iscsiadm -m discovery -t st -p server.ru-central1.internal

    - name: Set initiatorname
      ansible.builtin.copy:
        dest: /etc/iscsi/initiatorname.iscsi
        content: |
          InitiatorName=iqn.1994-05.com.redhat:{{ ansible_hostname }}

    - name: Grant access
      command: targetcli /iscsi/iqn.2018-09.ru.otus:storage.target00/tpg1/acls create iqn.1994-05.com.redhat:{{ ansible_hostname }}
      delegate_to: "{{ server }}"
      ignore_errors: true

    - name: Start iscsi
      ansible.builtin.systemd:
        name: iscsi
        state: started
        enabled: true
        daemon-reload: true

    - name: Login to target
      command: iscsiadm -m node -l -T iqn.2018-09.ru.otus:storage.target00

    - name: Stop stonith
      command: pcs property set stonith-enabled=false

    - name: Create DLM resource
      command: pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
      ignore_errors: true

    - command: pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
      ignore_errors: true

    - command: pcs constraint order start dlm-clone then clvmd-clone
      ignore_errors: true

    - name: Create volume group
      ansible.builtin.lvg:
        vg: cluster_vg
        vg_options: -Ay -cy
        pvs: /dev/sda
        state: present

    - name: Create logical volume
      ansible.builtin.lvol:
        lv: cluster_lv
        vg: cluster_vg
        resizefs: true
        size: +100%FREE
        active: true
        state: present

    - name: Format filesystem
      command: mkfs.gfs2 -O -j3 -p lock_dlm -t otuscluster:gfs2 /dev/cluster_vg/cluster_lv
      ignore_errors: true

    - name: Mount filesystem
      command: pcs resource create clusterfs ocf:heartbeat:Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2" fstype="gfs2" "options=noatime" op monitor interval=10s on-fail=ignore clone interleave=true
      ignore_errors: true

    - name: Add order constraint
      command: pcs constraint order start clvmd-clone then clusterfs-clone
      ignore_errors: true

    - name: Add colocation constraint
      command: pcs constraint colocation add clusterfs-clone with clvmd-clone
      ignore_errors: true
