---
- name: Prepare server
  become: true
  hosts: server
  tasks: []
    # - name: Install pacemaker, pcs, fence-agents
    #   ansible.builtin.apt:
    #     state: latest
    #     pkg:
    #       - pacemaker
    #       - pcs
    #       - fence-agents

- name: Prepare clients
  become: true
  hosts: clients
  tasks:
    - name: Install pacemaker
      ansible.builtin.yum:
        name:
          - pacemaker
          - pcs
          - fence-agents-all
    - ansible.builtin.systemd:
        name: pcsd.service
        state: started
        enabled: true
    - name: Set hacluster password
      ansible.builtin.user:
        name: hacluster
        password: $6$mysecretsalt$2PO0ANor95BEjI5Df1m7NeKkzF1s5xkb7wvuJKdQc59S1fY0JQcHadoT0wRjIhCDVcOTzkR8DDkmxn1rurx5w1
    - name: Auth to pcs
      command: pcs cluster auth {{ clients }} -u hacluster -p hacluster_pwd
    - name: Setup pcs
      command: pcs cluster setup --name otuscluster {{ clients }}
    - name: Enable pcs
      command: pcs cluster enable --all
    - name: Start pcs
      command: pcs cluster start --all
